# Generated by Django 5.0.2 on 2024-03-04 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_recipeingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
